"""Broker-agnostic interface and data types.

Strategy logic must depend on this module only — never on a concrete broker SDK.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal

Side = Literal["buy", "sell"]

#: order states that will never change again
TERMINAL_STATUSES = frozenset({"filled", "canceled", "rejected", "expired"})
#: order states still awaiting completion
OPEN_STATUSES = frozenset(
    {"new", "accepted", "pending_new", "accepted_for_bidding", "partially_filled", "held"}
)


@dataclass(frozen=True)
class Order:
    """An order request generated by the strategy (before submission)."""

    symbol: str
    qty: float
    side: Side
    order_type: str = "market"
    time_in_force: str = "day"
    client_order_id: str | None = None

    def __post_init__(self) -> None:
        if self.qty <= 0:
            raise ValueError(f"Order qty must be > 0, got {self.qty} for {self.symbol}")
        if self.side not in ("buy", "sell"):
            raise ValueError(f"Order side must be buy/sell, got {self.side!r}")


@dataclass
class BrokerOrder:
    """Broker-side view of an order (returned by submit/get_orders)."""

    id: str
    symbol: str
    side: str
    qty: float
    filled_qty: float
    status: str
    client_order_id: str | None = None
    filled_avg_price: float | None = None
    submitted_at: datetime | None = None

    @property
    def is_terminal(self) -> bool:
        return self.status in TERMINAL_STATUSES


@dataclass
class Position:
    symbol: str
    qty: float
    market_value: float
    avg_entry_price: float | None = None
    current_price: float | None = None
    unrealized_pl: float | None = None


@dataclass
class Account:
    equity: float
    cash: float
    buying_power: float
    currency: str = "USD"
    status: str = "UNKNOWN"
    raw: dict = field(default_factory=dict, repr=False)


class Broker(ABC):
    """Minimal broker interface used by the execution layer."""

    name: str = "abstract"

    @abstractmethod
    def get_account(self) -> Account: ...

    @abstractmethod
    def get_positions(self) -> list[Position]: ...

    @abstractmethod
    def get_orders(self, open_only: bool = True) -> list[BrokerOrder]: ...

    @abstractmethod
    def submit_order(self, order: Order) -> BrokerOrder: ...

    @abstractmethod
    def cancel_order(self, order_id: str) -> None: ...

    @abstractmethod
    def get_order(self, order_id: str) -> BrokerOrder: ...
